# Generated by Django 3.2.8 on 2022-07-15 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='transactions',
            fields=[
                ('id', models.TextField(db_column='tx_id', primary_key=True, serialize=False)),
                ('sender', models.TextField(blank=True, db_column='sender', null=True)),
                ('token_buy', models.TextField(blank=True, db_column='token_buy', null=True)),
                ('token_sell', models.TextField(blank=True, db_column='token_sell', null=True)),
                ('qty_buy', models.FloatField(blank=True, db_column='qty_buy', null=True)),
                ('qty_sell', models.FloatField(blank=True, db_column='qty_sell', null=True)),
                ('price', models.FloatField(blank=True, db_column='price', null=True)),
                ('timestamp', models.FloatField(blank=True, db_column='timestamp', null=True)),
                ('matched', models.FloatField(blank=True, db_column='matched', null=True)),
            ],
            options={
                'db_table': 'transactions',
            },
        ),
    ]
