# Generated by Django 3.2.8 on 2022-07-15 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_auto_20220715_1545'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactions',
            name='qty_sell',
        ),
        migrations.AddField(
            model_name='transactions',
            name='qty_other_side',
            field=models.FloatField(blank=True, db_column='qty_other_side', null=True),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='matched',
            field=models.TextField(blank=True, db_column='matched', null=True),
        ),
    ]
