# Generated by Django 3.2.8 on 2022-07-15 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_auto_20220715_1634'),
    ]

    operations = [
        migrations.CreateModel(
            name='pairs',
            fields=[
                ('id', models.TextField(db_column='pair_id', primary_key=True, serialize=False)),
                ('ccy1', models.TextField(blank=True, db_column='ccy1', null=True)),
                ('ccy2', models.TextField(blank=True, db_column='ccy2', null=True)),
            ],
            options={
                'db_table': 'pairs',
            },
        ),
    ]
