# Generated by Django 3.2.8 on 2022-07-18 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_balances'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='balances',
            new_name='balance',
        ),
    ]
