# Generated by Django 3.2.8 on 2022-07-18 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0007_rename_balance_balances'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='token_receive',
            field=models.FloatField(blank=True, db_column='token_receive', null=True),
        ),
        migrations.AddField(
            model_name='transactions',
            name='token_send',
            field=models.FloatField(blank=True, db_column='token_send', null=True),
        ),
    ]
