# Generated by Django 3.2.8 on 2022-07-18 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0008_auto_20220718_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='qty_receive',
            field=models.FloatField(blank=True, db_column='qty_receive', null=True),
        ),
        migrations.AddField(
            model_name='transactions',
            name='qty_send',
            field=models.FloatField(blank=True, db_column='qty_send', null=True),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='token_receive',
            field=models.TextField(blank=True, db_column='token_receive', null=True),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='token_send',
            field=models.TextField(blank=True, db_column='token_send', null=True),
        ),
    ]
